# .github/workflows/main.yml
name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: docker build -t alihamzehei/node:v1.${{ githun.run_number }} .
      - name: login dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: alihamzehei
          password: ${{ secrets.DOCKER_HUB }}
      - name: push image to docker hub
        run: docker push alihamzehei/node:v1.${{ githun.run_number }}
      - name: Release Changes
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.${{ githun.run_number }}
          release_name: Release v1.${{ githun.run_number }}
    
