# .github/workflows/main.yml
name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: docker build -t node/alihamzehei:v1 .
      - name: push image to docker
        uses: docker/login-action@v3.0.0
        with:
          username: alihamzehei
          password: aH1730220134
